// <auto-generated />
using System;
using Indt.Sistema.Seguros.Infra.DataBase.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Indt.Sistema.Seguros.Infra.DataBase.Migrations
{
    [DbContext(typeof(SegurosContext))]
    [Migration("20250808163746_AtualizandoRelacionamentoContratoParcelas")]
    partial class AtualizandoRelacionamentoContratoParcelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("idtsistemaseguro")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Indt.Sistema.Seguros.Infra.DataBase.Models.ContratoAgreggate.ContratoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataDeAlteracao")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("DateTime");

                    b.Property<DateTimeOffset>("DataFinal")
                        .HasColumnType("DateTimeOffset");

                    b.Property<DateTimeOffset>("DataInicial")
                        .HasColumnType("DateTimeOffset");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Prazo")
                        .HasColumnType("int");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Tb_Contrato", "idtsistemaseguro");
                });

            modelBuilder.Entity("Indt.Sistema.Seguros.Infra.DataBase.Models.ContratoAgreggate.ParcelaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("DateTime");

                    b.Property<DateTime?>("DataDeAlteracao")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("DateTime");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContratoId");

                    b.ToTable("Tb_Parcela", "idtsistemaseguro");
                });

            modelBuilder.Entity("Indt.Sistema.Seguros.Infra.DataBase.Models.PropostaAgreggate.PropostaEntity", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnoFabricacaoBem")
                        .IsRequired()
                        .HasColumnType("varchar(4)");

                    b.Property<string>("BairroEnderecoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<int>("CategoriaBem")
                        .HasColumnType("int");

                    b.Property<string>("CepEnderecoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<string>("ChassiBem")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CidadeEnderecoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("CorBem")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("DataDeAlteracao")
                        .HasColumnType("DateTime");

                    b.Property<DateTime>("DataDeCriacao")
                        .HasColumnType("DateTime");

                    b.Property<DateTimeOffset>("DataFim")
                        .HasColumnType("DateTimeOffset");

                    b.Property<DateTimeOffset>("DataInicio")
                        .HasColumnType("DateTimeOffset");

                    b.Property<DateTime>("DataNascimentoCliente")
                        .HasColumnType("DateTime");

                    b.Property<string>("DddContatoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("DescricaoCobertura")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DocumentoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EmailContatoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("EstadoEnderecoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(2)");

                    b.Property<bool>("FranquiaCobertura")
                        .HasColumnType("bit");

                    b.Property<string>("LimiteIdenizacaoCobertura")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("LogradouroEnderecoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<string>("MarcaBem")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("NumeroContatoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("NumeroEnderecoCliente")
                        .HasColumnType("int");

                    b.Property<string>("PlacaBem")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Prazo")
                        .HasColumnType("int");

                    b.Property<decimal>("PremioCobertura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusProposta")
                        .HasColumnType("int");

                    b.Property<int>("TipoSeguro")
                        .HasColumnType("int");

                    b.Property<string>("UtilizacaoBem")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFranquiaCobertura")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Tb_Proposta", "idtsistemaseguro");
                });

            modelBuilder.Entity("Indt.Sistema.Seguros.Infra.DataBase.Models.ContratoAgreggate.ContratoEntity", b =>
                {
                    b.HasOne("Indt.Sistema.Seguros.Infra.DataBase.Models.PropostaAgreggate.PropostaEntity", "Proposta")
                        .WithOne("Contrato")
                        .HasForeignKey("Indt.Sistema.Seguros.Infra.DataBase.Models.ContratoAgreggate.ContratoEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposta");
                });

            modelBuilder.Entity("Indt.Sistema.Seguros.Infra.DataBase.Models.ContratoAgreggate.ParcelaEntity", b =>
                {
                    b.HasOne("Indt.Sistema.Seguros.Infra.DataBase.Models.ContratoAgreggate.ContratoEntity", "ContratoEntity")
                        .WithMany("Parcelas")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContratoEntity");
                });

            modelBuilder.Entity("Indt.Sistema.Seguros.Infra.DataBase.Models.ContratoAgreggate.ContratoEntity", b =>
                {
                    b.Navigation("Parcelas");
                });

            modelBuilder.Entity("Indt.Sistema.Seguros.Infra.DataBase.Models.PropostaAgreggate.PropostaEntity", b =>
                {
                    b.Navigation("Contrato")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
