USE [master]
GO

/****** Object:  Database [IDTSeguro]    Script Date: 07/08/2025 16:20:34 ******/
CREATE DATABASE [IDTSeguro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IDTSeguro', FILENAME = N'/var/opt/mssql/data/IDTSeguro.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IDTSeguro_log', FILENAME = N'/var/opt/mssql/data/IDTSeguro_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IDTSeguro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IDTSeguro] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IDTSeguro] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IDTSeguro] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IDTSeguro] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IDTSeguro] SET ARITHABORT OFF 
GO

ALTER DATABASE [IDTSeguro] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IDTSeguro] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IDTSeguro] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IDTSeguro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IDTSeguro] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IDTSeguro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IDTSeguro] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IDTSeguro] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IDTSeguro] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IDTSeguro] SET  ENABLE_BROKER 
GO

ALTER DATABASE [IDTSeguro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IDTSeguro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IDTSeguro] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IDTSeguro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IDTSeguro] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IDTSeguro] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [IDTSeguro] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IDTSeguro] SET RECOVERY FULL 
GO

ALTER DATABASE [IDTSeguro] SET  MULTI_USER 
GO

ALTER DATABASE [IDTSeguro] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IDTSeguro] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IDTSeguro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IDTSeguro] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [IDTSeguro] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IDTSeguro] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [IDTSeguro] SET QUERY_STORE = ON
GO

ALTER DATABASE [IDTSeguro] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [IDTSeguro] SET  READ_WRITE 
GO


